### ISSUE TITLE
Ledetekster/instruksjoner for Min profil

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/webshop#224]
**Beskrivelse av bug**
WCAG 2.0 3.3.2 Ledetekster eller instruksjoner

- Redigering av epost: Ved aktivering av inputfelt plasseres ikke innsettingsmarkør på slutten av allerede utfylt epost
- [iOS/Android] Trykk på ikonene kunne gitt info om hvilken verdi disse har nå. F.ex trykk på person kunne listet ut "Fornavn Hans Etternavn Rotmo", eller epost kan gi "ikke utfylt". Det samme etter Lagre. Gi ut talemelding om status etter lagring.
- [iOS] Dersom du har et t:kort registrert og trykker på Fjern t:kort så flyttes fokus til siste tegn i t:kortet som er "X". Men advarselen om fjerning av t:kort blir ikke lest opp.

**Comment by gorandalum** [comment]
> Redigering av epost: Ved aktivering av inputfelt plasseres ikke innsettingsmarkør på slutten av allerede utfylt epost

Det fungerer hos meg i Chrome på desktop. På mobil får man ikke opp tastaturet automatisk, det er slått av på iOS/Android (av Apple/Google) at tastaturet kommer opp ved fokus. Brukeren må trykke på det fokuserte feltet for å få opp tastaturet, by design.

> [iOS/Android] Trykk på ikonene kunne gitt info om hvilken verdi disse har nå. F.ex trykk på person kunne listet ut "Fornavn Hans Etternavn Rotmo", eller epost kan gi "ikke utfylt".

Usikker på denne. Jeg ville ikke lagt til den teksten på ikonet i tillegg til at feltene var navigerbare for brukeren, det blir litt smør på flesk. 

>  Gi ut talemelding om status etter lagring.

La til at det kommer en melding "Profilen din ble oppdatert" etter man gjør endringer på Min Side. Bare si fra om man vil ha annen tekst.

> [iOS] Dersom du har et t:kort registrert og trykker på Fjern t:kort så flyttes fokus til siste tegn i t:kortet som er "X". Men advarselen om fjerning av t:kort blir ikke lest opp.

Hvor fokuset havner er litt hipp som happ ja, men i min testing blir advarselen lest opp som den skal. Jeg tror dette er forbedret siden denne saken ble opprettet.

**Comment by tormoseng** [comment]
Testet OK at "Profilen din ble oppdatert" leses opp + advarsel på fjerning av t:kort leses også opp. Ellers enig med Gøran.
